name: CI
on:
  pull_request:
  push:
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: 'sbt'
    - name: Build
      run: sbt package
    - uses: actions/upload-artifact@v2
      with:
        name: jars
        path: '*/target/*.jar'
        retention-days: 1
    
