name: CI
on:
  pull_request:
  push:
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: 'sbt'
    - name: Build
      run: sbt package
    - uses: actions/upload-artifact@v2
      with:
        name: jars
        path: 'target/*/*.jar'
        retention-days: 1
  release:
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    runs-on: ubuntu-latest
    needs: package
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: jars
      - name: Upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          tag="${GITHUB_REF#refs/tags/}"
          args=$(printf -- "-a %q " target/*/*.jar)
          hub release create $args -m "Release $tag" $tag
